### ISSUE TITLE
HitTest causes exception SharpDX

### ISSUE THREAD

**Issue by gregorsGit** [helix-toolkit/helix-toolkit#1190]
Hi,

sometimes I get this exception: 
System.IndexOutOfRangeException: Index was outside the bounds of the array.
   at HelixToolkit.Wpf.SharpDX.MeshGeometry3D.<get_Triangles>d__17.MoveNext()
   at HelixToolkit.Wpf.SharpDX.MeshGeometry3D.HitTest(RenderContext context, Matrix modelMatrix, Ray& rayWS, List`1& hits, Object originalSource)
   at HelixToolkit.Wpf.SharpDX.Model.Scene.MeshNode.OnHitTest(RenderContext context, Matrix totalModelMatrix, Ray& rayWS, List`1& hits)
   at HelixToolkit.Wpf.SharpDX.Model.Scene.GeometryNode.HitTest(RenderContext context, Ray rayWS, List`1& hits)
   at HelixToolkit.Wpf.SharpDX.Model.Scene.GroupNodeBase.OnHitTest(RenderContext context, Matrix totalModelMatrix, Ray& ray, List`1& hits)
   at HelixToolkit.Wpf.SharpDX.Model.Scene.GroupNode.OnHitTest(RenderContext context, Matrix totalModelMatrix, Ray& ray, List`1& hits)
   at HelixToolkit.Wpf.SharpDX.Model.Scene.SceneNode.HitTest(RenderContext context, Ray ray, List`1& hits)
   at HelixToolkit.Wpf.SharpDX.Model.Scene.GroupNodeBase.OnHitTest(RenderContext context, Matrix totalModelMatrix, Ray& ray, List`1& hits)
   at HelixToolkit.Wpf.SharpDX.Model.Scene.GroupNode.OnHitTest(RenderContext context, Matrix totalModelMatrix, Ray& ray, List`1& hits)
   at HelixToolkit.Wpf.SharpDX.Model.Scene.SceneNode.HitTest(RenderContext context, Ray ray, List`1& hits)
   at HelixToolkit.Wpf.SharpDX.IViewportExtensions.FindHits(IViewport3DX viewport, Vector2 position, List`1& hits)
   at HelixToolkit.Wpf.SharpDX.Viewport3DX.MouseDownHitTest(Point pt, InputEventArgs originalInputEventArgs)
   at HelixToolkit.Wpf.SharpDX.Viewport3DX.OnTouchDown(TouchEventArgs e)

Thanks

**Comment by holance** [comment]
You may want to check with your mesh data, it happens when triangle index is out of range

**Comment by gregorsGit** [comment]
Hi,
yes, i found in one model corrupted triangle indexes.
Thanks for this answer.
