### ISSUE TITLE
Exception on old graphic-card hardware sharpdx

### ISSUE THREAD

**Issue by gregorsGit** [helix-toolkit/helix-toolkit#1192]
Hi,

Description: The process was terminated due to an unhandled exception.
Exception Info: SharpDX.SharpDXException
   at SharpDX.Result.CheckError()
   at SharpDX.Direct2D1.D2D1.CreateFactory(SharpDX.Direct2D1.FactoryType, System.Guid, System.Nullable`1<SharpDX.Direct2D1.FactoryOptions>, IntPtr ByRef)
   at SharpDX.Direct2D1.Factory..ctor(SharpDX.Direct2D1.FactoryType, SharpDX.Direct2D1.DebugLevel)
   at HelixToolkit.Wpf.SharpDX.EffectsManager.Initialize(Int32)
   at HelixToolkit.Wpf.SharpDX.EffectsManager.Initialize()
   at HelixToolkit.Wpf.SharpDX.EffectsManager..ctor()
   at SimpleDemo.MainViewModel..ctor()

What is the reason for such exception on old AMD Graphics-Card HD4000er series.
Can I check something? 
Change settings in the effectmanager?

Please give me a hint.

Thanks

**Comment by holance** [comment]
Maybe because it does not support Directx 11.

**Comment by gregorsGit** [comment]
Hi,
this hardware supports only Directx 10.1 not 11.
Is there an easy way to detect and start in compatible/legacy mode without directx11 support?

**Comment by gregorsGit** [comment]
Addon:

device.FeatureLevel shows Level_11_0
**dxdiag.exe** shows 
on the first page.         DirectX Version: DirectX 11
on the Display page:    DDI Version: 10.1
On the DirectX Features there is
DirectDraw Acceleration: Not Available.

**Comment by gregorsGit** [comment]
Hi,
I found a solution for this.
https://stackoverflow.com/questions/50534483/sharpdx-no-such-interface-supported
I need to install the platformupdate from ms.
https://support.microsoft.com/en-us/help/2670838/platform-update-for-windows-7-sp1-and-windows-server-2008-r2-sp1
Now it works.
