### ISSUE TITLE
Various HelixToolkit.SharpDX.Core examples not building

### ISSUE THREAD

**Issue by lmcintyre** [helix-toolkit/helix-toolkit#1368]
Hi, trying to get a handle on the capabilities of the toolkit for a project. Been looking at some examples but some of the examples in the "HelixToolkit.SharpDX" solution give me a Fody error. For example, if I clone master, open "HelixToolkit.SharpDX.sln", and attempt to run ManipulatorDemo, I get this error:
```Severity	Code	Description	Project	File	Line	Suppression State
Error		Fody: An unhandled exception occurred:
Exception:
Failed to execute weaver C:\Users\Liam\.nuget\packages\propertychanged.fody\2.6.1\netclassicweaver\PropertyChanged.Fody.dll
Type:
System.Exception
StackTrace:
   at InnerWeaver.ExecuteWeavers() in C:\projects\fody\FodyIsolated\InnerWeaver.cs:line 208
   at InnerWeaver.Execute() in C:\projects\fody\FodyIsolated\InnerWeaver.cs:line 103
Source:
FodyIsolated
TargetSite:
Void ExecuteWeavers()
Method not found: 'Fody.TypeSystem Fody.BaseModuleWeaver.get_TypeSystem()'.
Type:
System.MissingMethodException
StackTrace:
   at ModuleWeaver.FindIsChangedEventInvokerMethodDefinition(TypeDefinition type, MethodDefinition& methodDefinition)
   at ModuleWeaver.RecursiveFindMethod(TypeDefinition typeDefinition) in C:\projects\propertychanged\PropertyChanged.Fody\IsChangedMethodFinder.cs:line 45
   at ModuleWeaver.FindIsChangedMethod() in C:\projects\propertychanged\PropertyChanged.Fody\IsChangedMethodFinder.cs:line 100
   at ModuleWeaver.Execute() in C:\projects\propertychanged\PropertyChanged.Fody\ModuleWeaver.cs:line 19
   at InnerWeaver.ExecuteWeavers() in C:\projects\fody\FodyIsolated\InnerWeaver.cs:line 204
Source:
PropertyChanged.Fody
TargetSite:
Boolean FindIsChangedEventInvokerMethodDefinition(Mono.Cecil.TypeDefinition, Mono.Cecil.MethodDefinition ByRef)	ManipulatorDemo			
```
This is with Fody version 3.0.4.0, same as the passing build from AppVeyor. If someone can reproduce (or worse, can't reproduce) and can assist I'd love to get this building.

**Comment by holance** [comment]
Make sure you are using VS2019 and restore the nuget packages on the solution.

**Comment by lmcintyre** [comment]
Yep, using VS2019. Restoring Nuget packages or not, I get the same issue.

**Comment by holance** [comment]
Maybe it is caused by this: https://github.com/Fody/Costura/issues/301

**Comment by lmcintyre** [comment]
I am unsure. However, I did solve this by upgrading the Fody and the PropertyChanged.Fody packages to the latest versions from Nuget.

**Comment by billpeet** [comment]
Same issue here - every example that uses PropertyChanged.Fody failed to build for me, until I updated by Fody/PropertyChanged.Fody packages

**Comment by holance** [comment]
Please try again with latest source
