### ISSUE TITLE
SharpDX.SharpDXException [0x80070057] when creating a DiffuseMap from an image

### ISSUE THREAD

**Issue by A1exG** [helix-toolkit/helix-toolkit#2117]
Hi all. When creating a DiffuseMap from an image I get an error that I cannot process. An error occurs when assigning a created material to a model.

![image](https://github.com/helix-toolkit/helix-toolkit/assets/54076911/34aa2739-7806-40f0-9291-8f26fc6e9fc1)

Exception classes:   
   SharpDX.SharpDXException
Exception messages: 
   HRESULT: [0x80070057], Module: [General], ApiCode: [E_INVALIDARG/Invalid Arguments], Message: Параметр задан неверно.

Stack Traces:
   at SharpDX.Direct3D11.Device.CreateTexture2D(Texture2DDescription& descRef, DataBox[] initialDataRef, Texture2D texture2DOut)
   at SharpDX.Toolkit.Graphics.Texture2D.New(Device device, Image image, TextureFlags flags, ResourceUsage usage)
   at SharpDX.Toolkit.Graphics.Texture.Load(Device device, Stream stream, TextureFlags flags, ResourceUsage usage)
   at HelixToolkit.SharpDX.Core.Utilities.TextureLoader.FromMemoryAsShaderResource(Device device, Stream memory, Boolean disableAutoGenMipMap)
   at HelixToolkit.SharpDX.Core.Utilities.ShaderResourceViewProxy.HandleTextureContent(TextureInfo content, Boolean createSRV, Boolean enableAutoGenMipMap)
   at HelixToolkit.SharpDX.Core.TextureResourceManager.Register(TextureModel textureModel, Boolean enableAutoGenMipMap)
   at HelixToolkit.SharpDX.Core.Model.PhongMaterialVariables.<OnInitialPropertyBindings>b__102_23()
   at HelixToolkit.SharpDX.Core.Model.MaterialVariable.Initialize()

**Comment by A1exG** [comment]
PC configuration:
AMD Ryzen 5 5600H with Radeon Graphics
NVidia RTX 3050 Laptop

**Comment by A1exG** [comment]
This is not an isolated case. Relevant for large images.
But multiple images with +- the same dimensions work fine

**Comment by holance** [comment]
Please provide a sample of the image or a sample project so we can debug.

**Comment by A1exG** [comment]
> Please provide a sample of the image or a sample project so we can debug.

@holance I sent the image to your email from my github profile, but due to the size of the image I couldn’t post it here

**Comment by A1exG** [comment]
@holance, Were you able to run the example with this image?

I have a laptop with 2 video cards. The nvidia settings are set to use an external video card. When creating the EffectManager, I checked that the device was taken correctly.

**Comment by holance** [comment]
I am not able to load the image as well.

**Comment by holance** [comment]
Maximum resolution on U/V for texture resource is 16384. Your image resolution is too big. 
https://www.google.com/url?sa=t&rct=j&q=&esrc=s&source=web&cd=&ved=2ahUKEwiH9q2Bj-WDAxVnD1kFHQXABzkQFnoECAgQAw&url=https%3A%2F%2Flearn.microsoft.com%2Fen-us%2Fwindows%2Fwin32%2Fdirect3d11%2Foverviews-direct3d-11-resources-limits&usg=AOvVaw3k15O_Beqf3a_Pq6DdPMAY&opi=89978449

**Comment by A1exG** [comment]
@holance, I changed the resolution and it worked for me. Thank you!
