### ISSUE TITLE
effects dll error when using sharpDX

### ISSUE THREAD

**Issue by issamouawad** [helix-toolkit/helix-toolkit#259]
I am trying to use helix3D with sharpdx , but I got this error 
`System.DllNotFoundException: Unable to find [sharpdx_direct3d11_1_effects_x64.dll] in the PATH
   at SharpDX.Utilities.LoadLibrary(String dllName)
   at SharpDX.Direct3D11.D3DX11Effects.get_DllHandle0()
   at SharpDX.Direct3D11.D3DX11Effects.get_D3DX11CreateEffectFromMemory_()
   at SharpDX.Direct3D11.D3DX11Effects.CreateEffectFromMemory(IntPtr dataRef, PointerSize dataLength, Int32 fXFlags, Device deviceRef, Effect effectOut)
   at SharpDX.Direct3D11.Effect..ctor(Device device, Byte[] effectByteCode, EffectFlags fxFlags)
   at HelixToolkit.Wpf.SharpDX.DefaultEffectsManager.RegisterEffect(Byte[] shaderEffectBytecode, RenderTechnique[] techniques, EffectFlags eFlags) in C:\projects\helix-toolkit\Source\HelixToolkit.Wpf.SharpDX\Controls\Effects.cs:line 176
   at HelixToolkit.Wpf.SharpDX.DefaultEffectsManager.RegisterEffect(String shaderEffectString, RenderTechnique[] techniques, ShaderFlags sFlags, EffectFlags eFlags) in C:\projects\helix-toolkit\Source\HelixToolkit.Wpf.SharpDX\Controls\Effects.cs:line 324
   at HelixToolkit.Wpf.SharpDX.DefaultEffectsManager.RegisterDefaultLayoutsAndEffects(String shaderEffectString, InputLayout& defaultInputLayout, InputLayout& cubeMapInputLayout) in C:\projects\helix-toolkit\Source\HelixToolkit.Wpf.SharpDX\Controls\Effects.cs:line 300
   at HelixToolkit.Wpf.SharpDX.DefaultEffectsManager.InitEffects() in C:\projects\helix-toolkit\Source\HelixToolkit.Wpf.SharpDX\Controls\Effects.cs:line 166
   at HelixToolkit.Wpf.SharpDX.DefaultEffectsManager..ctor(IRenderTechniquesManager renderTechniquesManager) in C:\projects\helix-toolkit\Source\HelixToolkit.Wpf.SharpDX\Controls\Effects.cs:line 72
   at HelixToolkit.Wpf.SharpDX.DPFCanvas.StartD3D() in C:\projects\helix-toolkit\Source\HelixToolkit.Wpf.SharpDX\Controls\DPFCanvas.cs:line 276
   at HelixToolkit.Wpf.SharpDX.DPFCanvas.OnLoaded(Object sender, RoutedEventArgs e) in C:\projects\helix-toolkit\Source\HelixToolkit.Wpf.SharpDX\Controls\DPFCanvas.cs:line 233`

when I use latest version of SharpDX (without helix) it's working fine(version 3.0.0), 
but helix3d is using version 2.6.3 which seems to be producing the error, and helix3d won't compile with version 3 at all ,
any solution ?

**Comment by dhintermann** [comment]
The dll is added to your project in visual studio, when you add the dependency HelixToolkit.Wpf.SharpDX with the nuget package manager. On "properties" select "copy if newer" for the "copy to output directory" option in visual studio for this file. Alternatively, you could copy the dll manually from the visual studio solution package directory. It is in SharpDX.Direct3D11.Effects folder.

**Comment by SiNeumann** [comment]
You most certainly miss the d3d_compiler43.dll which was part of VisualStudio SDK (I think up to version 2013) on  a vanilla Windows 10 machine with Visual Studio 2015 ,this is missing, this also could happen for machines without any VS installed. Solution is to install DirectXEndUserRuntime https://www.microsoft.com/en-us/download/details.aspx?displaylang=en&id=35 .

**Comment by holance** [comment]
Closed. Effects framework obsolete.
