### ISSUE TITLE
Is Windows 10 minimum OS for Helix-SharpDX?

### ISSUE THREAD

**Issue by mk48** [helix-toolkit/helix-toolkit#394]
I just installed the latest version(1.0.0-unstable 1030) of HelixToolkit.Wpf.SharpDX using myget.org.
Following DLLs added in project
- sharpdx_direct3d11_1_effects_x64.dll
- sharpdx_direct3d11_1_effects_arm.dll
- sharpdx_direct3d11_1_effects_x86.dll

These DLLs require D3DCOMPILER_47.DLL, which is part of Win 10 SDK (latest DirectX)

So, Do I need Win 10 OS to run the latest Helix-SharpDX?
Is there any way to get the dll file 'D3DCOMPILER_47.DLL' to use?

**Screens**

I installed the below version
![image](https://cloud.githubusercontent.com/assets/3082469/21172482/407b6c9e-c1f8-11e6-863d-c060c43ed9bf.png)

Getting below error message
![image](https://cloud.githubusercontent.com/assets/3082469/21172498/5848e43c-c1f8-11e6-922c-a6c3e3affaee.png)
Error msg:
System.DllNotFoundException: Unable to load DLL 'sharpdx_direct3d11_1_effects_x86.dll': The specified module could not be found. (Exception from HRESULT: 0x8007007E)
   at SharpDX.Direct3D11.D3DX11Effects.D3DX11CreateEffectFromMemory_11_1_x86(IntPtr dataPointer, IntPtr dataLength, Int32 fxFlags, IntPtr devicePtr, IntPtr& effectOut, IntPtr srcName)
   at SharpDX.Direct3D11.D3DX11Effects.CreateEffectFromMemory(IntPtr dataRef, PointerSize dataLength, Int32 fXFlags, Device deviceRef, Effect effectOut, String srcName)
   at SharpDX.Direct3D11.Effect..ctor(Device device, Byte[] effectByteCode, EffectFlags fxFlags, String srcName)
   at HelixToolkit.Wpf.SharpDX.DefaultEffectsManager.RegisterEffect(Byte[] shaderEffectBytecode, RenderTechnique[] techniques, EffectFlags eFlags) in C:\projects\helix-toolkit\Source\HelixToolkit.Wpf.SharpDX\Controls\Effects.cs:line 192
   at HelixToolkit.Wpf.SharpDX.DefaultEffectsManager.RegisterEffect(String shaderEffectString, RenderTechnique[] techniques, ShaderFlags sFlags, EffectFlags eFlags) in C:\projects\helix-toolkit\Source\HelixToolkit.Wpf.SharpDX\Controls\Effects.cs:line 340
   at HelixToolkit.Wpf.SharpDX.DefaultEffectsManager.RegisterDefaultLayoutsAndEffects(String shaderEffectString, InputLayout& defaultInputLayout, InputLayout& cubeMapInputLayout) in C:\projects\helix-toolkit\Source\HelixToolkit.Wpf.SharpDX\Controls\Effects.cs:line 316
   at HelixToolkit.Wpf.SharpDX.DefaultEffectsManager.InitEffects() in C:\projects\helix-toolkit\Source\HelixToolkit.Wpf.SharpDX\Controls\Effects.cs:line 181
   at HelixToolkit.Wpf.SharpDX.DefaultEffectsManager..ctor(IRenderTechniquesManager renderTechniquesManager) in C:\projects\helix-toolkit\Source\HelixToolkit.Wpf.SharpDX\Controls\Effects.cs:line 72
   at HelixToolkit.Wpf.SharpDX.DPFCanvas.StartD3D() in C:\projects\helix-toolkit\Source\HelixToolkit.Wpf.SharpDX\Controls\DPFCanvas.cs:line 322
   at HelixToolkit.Wpf.SharpDX.DPFCanvas.OnLoaded(Object sender, RoutedEventArgs e) in C:\projects\helix-toolkit\Source\HelixToolkit.Wpf.SharpDX\Controls\DPFCanvas.cs:line 279

Effects DLLs require *47.dll
![image](https://cloud.githubusercontent.com/assets/3082469/21172530/7d861a44-c1f8-11e6-93a2-8cabfaf3763c.png)

**Comment by holance** [comment]
You need to install the windows 10 sdk if you are using Windows 7. Then needs to add the D3DCompiler47.dll path into the system environment path, or copy the D3DCompiler47.dll  into your own binary folder. 

Make sure to copy the correct version(x86 or x64) of the D3DCompiler47.dll depending on your program build. 

Build with prefer x86 needs x86 dll. Any cpu uses x64 dll.

**Comment by mk48** [comment]
@holance  Thanks for the quick reply.

Is D3DCompiler47.dll the only required file?
Or
Do I have to install Win10 SDK in production system also?

**Comment by holance** [comment]
You can try to uninstall the Win10SDK and copy the dll into your bin folder. I think it should work.

**Comment by holance** [comment]
The latest checkin #395 should address this issue. Closed.

**Comment by pipited07** [comment]
@holance  My OS is Win10. I had the same question ,when I downloaded the stable version on Nuget and fixed it by adding the sharpdx_direct3d11_1_effects_x64.dll into the project of  bin file(Debug & Release). 
Now I download from Myget, and  I can't fix it by add sharpdx_direct3d11_1_effects_x64.dll(or d3dcompiler_47.dll). Do you have any idea?

**Comment by holance** [comment]
Windows 10 should be able to run just fine. Are you sure you are getting
the same error? Are you able to run examples from the source code?

**Comment by pipited07** [comment]
@holance  I'm pretty sure I get the same error. The error message is exactly same. I can run the sample code normally. I tried to created a new wpf project and imported by  Myget(unstable version) or Nuget , both had the error in view port. But the Nuget version I can fix by adding the sharpdx_direct3d11_1_effects_x86.dll in bin folder.

**Comment by holance** [comment]
Try to uncheck the prefer x86 in your the project build
setting

**Comment by pipited07** [comment]
@holance  You mean the target plateform change to x64 or?

**Comment by holance** [comment]
Try it

**Comment by pipited07** [comment]
@holance  No, It doesn't work no matter it is x86 or x64.

**Comment by holance** [comment]
Did you use unreleased version or the stable one from myget?

**Comment by JeremyAnsel** [comment]
I can reproduce the error with this code:
````csharp
try
{
    var renderTechniquesManager = new HelixToolkit.Wpf.SharpDX.DefaultRenderTechniquesManager();
    var effectsManager = new HelixToolkit.Wpf.SharpDX.DefaultEffectsManager(renderTechniquesManager);
}
catch (Exception ex)
{
    Console.WriteLine(ex);
}
````
I can fix it by adding the effects dll:
- sharpdx_direct3d11_1_effects_arm.dll
- sharpdx_direct3d11_1_effects_x64.dll
- sharpdx_direct3d11_1_effects_x86.dll

**Comment by pipited07** [comment]
@holance  It work after I updated it and put the file mentioned above into the bin folder.Thanks for your reply.
