### ISSUE TITLE
SharpDX.Direct3D11.D3DX11Effects.CreateEffectFromMemory NullReferenceException

### ISSUE THREAD

**Issue by mk48** [helix-toolkit/helix-toolkit#445]
I am getting below error while opening window

![image](https://cloud.githubusercontent.com/assets/3082469/23067817/f78ed49e-f546-11e6-9e47-58afa9d9645b.png)

Any idea about the error?

System.NullReferenceException: Object reference not set to an instance of an object.
   at SharpDX.Direct3D11.D3DX11Effects.CreateEffectFromMemory(IntPtr dataRef, PointerSize dataLength, Int32 fXFlags, Device deviceRef, Effect effectOut, String srcName)
   at SharpDX.Direct3D11.Effect..ctor(Device device, Byte[] effectByteCode, EffectFlags fxFlags, String srcName)
   at HelixToolkit.Wpf.SharpDX.DefaultEffectsManager.RegisterEffect(Byte[] shaderEffectBytecode, RenderTechnique[] techniques, EffectFlags eFlags)
   at HelixToolkit.Wpf.SharpDX.DefaultEffectsManager.RegisterEffect(String shaderEffectString, RenderTechnique[] techniques, ShaderFlags sFlags, EffectFlags eFlags)
   at HelixToolkit.Wpf.SharpDX.DefaultEffectsManager.RegisterDefaultLayoutsAndEffects(String shaderEffectString, InputLayout& defaultInputLayout, InputLayout& cubeMapInputLayout)
   at HelixToolkit.Wpf.SharpDX.DefaultEffectsManager.InitEffects()
   at HelixToolkit.Wpf.SharpDX.DefaultEffectsManager..ctor(IRenderTechniquesManager renderTechniquesManager)
   at HelixToolkit.Wpf.SharpDX.DPFCanvas.StartD3D()
   at HelixToolkit.Wpf.SharpDX.DPFCanvas.OnLoaded(Object sender, RoutedEventArgs e)

**Comment by holance** [comment]
Try to debug if the device gets created correctly.

**Comment by beketata** [comment]
It was the same issue with my old laptop based on the Intel Mobile 945 video.
The proplem it here:
```
private static Adapter GetBestAdapter( out int bestAdapterIndex )
{
...
  var level = global::SharpDX.Direct3D11.Device.GetSupportedFeatureLevel(item);
  if( level < DefaultEffectsManager.MinimumFeatureLevel )
    continue;
```
in the "HelixToolkit.Wpf.SharpDX\Controls\Effect.cs"
because the value returned by **GetSupportedFeatureLevel()** is less than **DefaultEffectsManager.MinimumFeatureLevel**.

**Comment by holance** [comment]
No longer use effect framework in new 2.0. Close this issue for now.
