### ISSUE TITLE
Helix SharpDX: 10000 GDI Object limit with BillboardTextSingle3D

### ISSUE THREAD

**Issue by avinabmalla** [helix-toolkit/helix-toolkit#607]
Hi, 
I am using helix toolkit for a structural analysis program and its great!
Unfortunately when I try to create large models with lots of labels(BillboardTextSingle3D) the application quickly hits the 10000 GDI Object limit and crashes with the MILERR_WIN32ERROR exception.

The stack trace is as below:

 at System.Windows.Media.Imaging.RenderTargetBitmap.FinalizeCreation()
		 at System.Windows.Media.Imaging.RenderTargetBitmap..ctor(Int32 pixelWidth, Int32 pixelHeight, Double dpiX, Double dpiY, PixelFormat pixelFormat)
		 at HelixToolkit.Wpf.SharpDX.BitmapExtension.ToBitmapSource(TextBlock element, Boolean freeze) in C:\\projects\\helix-toolkit\\Source\\HelixToolkit.Wpf.SharpDX\\Extensions\\BitmapExtension.cs:line 19
		 at HelixToolkit.Wpf.SharpDX.BitmapExtension.StringToBitmapSource(String str, Int32 fontSize, Color foreground, Color background, FontFamily fontFamily, FontWeight fontWeight, FontStyle fontStyle, Thickness padding) in C:\\projects\\helix-toolkit\\Source\\HelixToolkit.Wpf.SharpDX\\Extensions\\BitmapExtension.cs:line 66
		 at HelixToolkit.Wpf.SharpDX.BillboardSingleText3D.DrawTexture() in C:\\projects\\helix-toolkit\\Source\\HelixToolkit.Wpf.SharpDX\\Model\\Geometry\\BillboardSingleText3D.cs:line 129
		 at HelixToolkit.Wpf.SharpDX.BillboardTextModel3D.CreateBillboardVertexArray() in C:\\projects\\helix-toolkit\\Source\\HelixToolkit.Wpf.SharpDX\\Model\\Elements3D\\BillboardTextModel3D.cs:line 445
		 at HelixToolkit.Wpf.SharpDX.BillboardTextModel3D.OnCreateGeometryBuffers() in C:\\projects\\helix-toolkit\\Source\\HelixToolkit.Wpf.SharpDX\\Model\\Elements3D\\BillboardTextModel3D.cs:line 284
		 at HelixToolkit.Wpf.SharpDX.BillboardTextModel3D.OnAttach(IRenderHost host) in C:\\projects\\helix-toolkit\\Source\\HelixToolkit.Wpf.SharpDX\\Model\\Elements3D\\BillboardTextModel3D.cs:line 329
		 at HelixToolkit.Wpf.SharpDX.Element3D.Attach(IRenderHost host) in C:\\projects\\helix-toolkit\\Source\\HelixToolkit.Wpf.SharpDX\\Model\\Elements3D\\AbstractElements3D\\Element3D.cs:line 163
		 at HelixToolkit.Wpf.SharpDX.CompositeModel3D.ChildrenChanged(Object sender, NotifyCollectionChangedEventArgs e) in C:\\projects\\helix-toolkit\\Source\\HelixToolkit.Wpf.SharpDX\\Model\\Elements3D\\CompositeModel3D.cs:line 154
		 at System.Collections.ObjectModel.ObservableCollection`1.OnCollectionChanged(NotifyCollectionChangedEventArgs e)
		 at System.Collections.ObjectModel.ObservableCollection`1.InsertItem(Int32 index, T item)
		 at HelixToolkit.Wpf.SharpDX.ItemsModel3D.ItemsModel3D_CollectionChanged(Object sender, NotifyCollectionChangedEventArgs e) in C:\\projects\\helix-toolkit\\Source\\HelixToolkit.Wpf.SharpDX\\Model\\Elements3D\\ItemsModel3D.cs:line 343
		 at System.Collections.ObjectModel.ObservableCollection`1.OnCollectionChanged(NotifyCollectionChangedEventArgs e)
		 at System.Collections.ObjectModel.ObservableCollection`1.InsertItem(Int32 index, T item)

**Comment by holance** [comment]
Unfortunately, there is no simple fix for this issue. Currently we are using GDI to draw the bitmap for text texture in BillboardTextSingle3D. Unless you can provide your own text texture drawing functions.

If you don't care about the text style or hittest etc, use BillboardText3D instead of BillboardTextSingle3D and adds the text infos.

**Comment by avinabmalla** [comment]
Thanks for your reply. I did manage to solve this problem by drawing the text on a bitmap using System.Drawing and then using it as the texture for BillboardSingleImage3D. This method requires windows forms dependency as I'm using TextRenderer.MeasureText to calculate the bitmap size. Perhaps you can come up with a better solution.

`class BillboardImageText3D: BillboardSingleImage3D
	{

		public string Text { get; set; }
		public Font Font { get; set; }
		public System.Drawing.Brush Brush { get; set; }

		public BillboardImageText3D(string text, Font font, System.Drawing.Brush brush):base()
		{
			Text = text;
			Font = font;
			Brush = brush;
			Texture = GetTextureBitmap();
			Width = Texture.PixelWidth;
			Height = Texture.PixelHeight;
			MaskColor = Color4.Black;
		}

		private Bitmap GetTexture()
		{
			var size = TextRenderer.MeasureText(Text, Font);
			var bmp = new Bitmap(size.Width, size.Height );


			RectangleF rectf = new RectangleF(0, 0, size.Width, size.Height);
			Graphics g = Graphics.FromImage(bmp);
			g.DrawString(Text, Font, Brush, rectf);
			g.Flush();
			return bmp;
		}

		public BitmapSource GetTextureBitmap()
		{
			var bitmap = GetTexture();
			var bitmapData = bitmap.LockBits(
				new System.Drawing.Rectangle(0, 0, bitmap.Width, bitmap.Height),
				System.Drawing.Imaging.ImageLockMode.ReadOnly, bitmap.PixelFormat);

			var bitmapSource = BitmapSource.Create(
				bitmapData.Width, bitmapData.Height,
				bitmap.HorizontalResolution, bitmap.VerticalResolution,
				PixelFormats.Bgr32, null,
				bitmapData.Scan0, bitmapData.Stride * bitmapData.Height, bitmapData.Stride);

			bitmap.UnlockBits(bitmapData);
			return bitmapSource;
		}
	}`

**Comment by holance** [comment]
2.0 will change to use WIC and Direct2D to draw text texture. #609
